  
  name: CI (Kiểm định)

  on: 
    push: 
      branches: ["main"]
    pull_request:
      branches: ["main"]

  jobs:
    Test:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: ["22.x"]
      
      steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{matrix.node-version}}
          uses: actions/setup-node@v4
          with:
            node-version: ${{matrix.node-version}}
            cache: 'npm'
        - run: npm ci 
        - name: Test CodeQL
          uses: github/codeql-action/init@v3
          with:
            languages: javascript, typescript
        - uses: github/codeql-action/autobuild@v3
        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v3
        - run: npm run test
        - name: Auth Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: |
              ${{secrets.DOCKERHUB_USERNAME}}/my-app-demo:${{github.sha}}
              ${{secrets.DOCKERHUB_USERNAME}}/my-app-demo:main
        - name: Notify Slack
          if: always()
          uses: slackapi/slack-github-action@v1.24.0
          with:
            payload: |
              {
                "text": "${{ job.status == 'success' && '✅ Kiểm định CI (Nhánh Main) Thành Công!' || '❌ CI/CD Pipeline Thất Bại!' }}\n- Nhánh (Branch): `${{ github.ref_name }}`\n- Người thực hiện: `${{ github.actor }}`\n- Xem chi tiết: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }
          env: 
            SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
